### ISSUE TITLE
不支持nii医疗文件

### ISSUE THREAD

**Issue by FjjRichard** [PaddleCV-SIG/MedicalSeg#30]
不支持nii医疗文件，nii和nii.gz是常见的医疗文件格式后缀名  ，两种文件基本一样
PaddleSeg3D/tools/prepare.py文件中
`    @staticmethod
    def load_medical_data(f):
        """
        load data of different format into numpy array

        f: the complete path to the file that you want to load

        """
        filename = f.split("/")[-1]
        if "nii.gz" in filename:   #->**if "nii.gz"  or "nii" in filename:**
            f_np = nib.load(f).get_fdata(dtype=np.float32)
        elif "nrrd" in filename:
            f_np, _ = nrrd.read(f)
        elif "mhd" in filename or "raw" in filename:
            itkimage = sitk.ReadImage(f)
            f_np = sitk.GetArrayFromImage(itkimage)
            # shuffle the dimensions to get axis in the order z, y, x
            f_np = np.transpose(
                f_np, [2, 1, 0]
            )  # TODO  check if this suits to other datasets, this is needed in luna16_lobe51
        else:
            raise NotImplementedError

        return f_np`

**Comment by linhandev** [comment]
正在弄，这两天就会添加

**Comment by shiyutang** [comment]
Added to the prepare, thanks for your advice :)
